### PR TITLE
fix: Add csv.gz

### PR DESCRIPTION
**Pull request by CharlesNepote**
### What
Add csv.gz link.

### CODE REVIEW

**Comment by CharlesNepote** [comment]
Solve https://github.com/openfoodfacts/openfoodfacts-server/issues/6443

**Comment by alexgarel** [comment]
@teolemon can we merge even if the actions fails ? (They do not seem relevant to me…)

**Comment by teolemon** [comment]
Yes

**Review by alexgarel — APPROVED** [review]
:+1:

**Comment by CharlesNepote** [comment]
Who will deploy this?

**Comment by alexgarel** [comment]
Good question. @stephanegigandet or @teolemon one of you do handle this usually ?

**Comment by stephanegigandet** [comment]
I will deploy it.

**Comment by stephanegigandet** [comment]
Done.

For reference, here is the current process (manual) on off1:

As the off user (not as root):

cd /home/off/openfoodfacts-web
git status
-> make sure it is the main branch
git pull
cp -a html lang /srv/off/

**Pull request merged**
