### PR TITLE
feat: finish ptbr translations

### PR DESCRIPTION
**Pull request by danizavtz**
### What
- There is no issue that address this issue, but I can create.

### CODE REVIEW

**Comment by teolemon** [comment]
no they are not (I disabled that because we had cross-contamination issues with bad strings)
I'll upload them manually

**Comment by alexgarel** [comment]
@danizavtz thank you a lot. Next contribution should be through crowdin: https://crowdin.com/project/openfoodfacts

**Comment by danizavtz** [comment]
I'm on it, just finished the translations in crowdin app. Are there anything I can do with this PR?

**Comment by teolemon** [comment]
It's conflicted. If you have translated on Crowdin, your work should already be in the main branch

**Pull request closed without merging**
